" Start without a toolbar or menu or scrollbars (right, left and bottom " scrollbars)
set guioptions-=T
set guioptions-=m
set guioptions-=l
set guioptions-=b
set guioptions-=L
set guioptions-=r

" GVim options:
if has("gui_gtk2")
   set guifont=Monospace\ 9

   " Ctrl+c for copy in visual and normal modes:
   imap <C-c> <ESC>"+y
   map <C-c> "+y
   " TODO: How to copy from command mode?

   " Ctrl+v for paste:
   imap <C-v> <Esc>"+gp
   map <C-v> "+gP
   cmap <C-v> <C-r>*

   " Ctrl + x for cut
   imap <C-x> <Esc>"+x
   map <C-x> "+x

   " Close file
   " map <C-w> :q<CR>

   " New tab
   map <C-T> :tabnew<CR>

   " Functions to Rearrange tabs
   function! TabLeft()
       let tab_number = tabpagenr() - 1
       if tab_number == 0
           execute "tabm" tabpagenr('$') - 1
       else
           execute "tabm" tab_number - 1
       endif
   endfunction
   command! TabLeft call TabLeft(),
   :map <C-S-PageUp> :TabLeft<cr>
   
   function! TabRight()
       let tab_number = tabpagenr() - 1
       let last_tab_number = tabpagenr('$') - 1
       if tab_number == last_tab_number
           execute "tabm" 0
       else
           execute "tabm" tab_number + 1
       endif
   endfunction
   command! TabRight call TabRight()
   :map <C-S-PageDown> :TabRight<cr>
endif


if has("gui_macvim")
   " MacVim stuff
endif
