" Start without a toolbar or menu or scrollbars (right, left and bottom " scrollbars)
set guioptions-=T
set guioptions-=m
set guioptions-=l
set guioptions-=b
set guioptions-=L
set guioptions-=r

" GVim options:
if has("gui_gtk2")
   set guifont=Monospace\ 9

   " Ctrl+c for copy in visual and normal modes:
   imap <C-c> <ESC>"+y
   map <C-c> "+y
   " TODO: How to copy from command mode?

   " Ctrl+v for paste:
   imap <C-v> <Esc>"+gp
   map <C-v> "+gP
   cmap <C-v> <C-r>*

   " Ctrl+v is normally visual block mode, change to Alt+v
   noremap <A-v> <C-v>

   " Ctrl + x for cut
   imap <C-x> <Esc>"+x
   map <C-x> "+x

   " Close file
   " map <C-w> :q<CR>

   " Control-Shift-F for Ack
   map <C-F> :Ack<space>-ai<space>

   " Switch Windows
   map <C-h> <C-w>h
   map <C-j> <C-w>j
   map <C-k> <C-w>k
   map <C-l> <C-w>l

   
   " Jump to companion file (*.cpp to *.hpp and so on)
   map <C-S-Up> :FSHere<CR>

   " Open markup previews in chromium
   let g:HammerBrowser = 'google-chrome'

   map <C-z> :GundoToggle<CR>

   " New tab
   map <C-T> :tabnew<CR>

   " Resize windows
   map <A-Right> <C-W>>
   map <A-Left> <C-W><
   map <A-Up> <C-W>+
   map <A-Down> <C-W>-

   " Functions to Rearrange tabr
   function! TabLeft()
       let tab_number = tabpagenr() - 1
       if tab_number == 0
           execute "tabm" tabpagenr('$') - 1
       else
           execute "tabm" tab_number - 1
       endif
   endfunction
   command! TabLeft call TabLeft(),
   :map <C-S-PageUp> :TabLeft<cr>
   
   function! TabRight()
       let tab_number = tabpagenr() - 1
       let last_tab_number = tabpagenr('$') - 1
       if tab_number == last_tab_number
           execute "tabm" 0
       else
           execute "tabm" tab_number + 1
       endif
   endfunction
   command! TabRight call TabRight()
   :map <C-S-PageDown> :TabRight<cr>
endif


if has("gui_macvim")
   " Control-Shift-F for Ack
   map <D-F> :Ack<space>-ai<space>

   " alt+/ toggles comments:
   map ÷ :TComment<cr> 
   imap ÷ <c-o>:TComment<cr>
   vmap ÷ :TCommentMaybeInline<cr>

   " Jump to companion file (*.cpp to *.hpp and so on)
   map <D-S-Up> :FSHere<CR>
   
   " Switch windows
   " macmenu &MacVim.Hide\ MacVim key=<nop> " This unmap won't work, go to system preferences and bind Hide MacVim to something else.
   map <D-h> <C-w>h
   map <D-j> <C-w>j
   map <D-k> <C-w>k
   macmenu &Tools.List\ Errors key=<nop>
   map <D-l> <C-w>l
   
   " Resize windows
   map <A-Right> <C-W>>
   map <A-Left> <C-W><
   map <A-Up> <C-W>+
   map <A-Down> <C-W>-
endif
