desc "Install tmux"
task :install do
   sh "sudo apt-add-repository ppa:simono/dev-tools"
   sh "sudo apt-get update"
   sh "sudo apt-get install tmux"
end

desc "Creates needed symlinks"
task :link do
   `mv -f ~/.tmux.conf ~/.tmux.conf.old 2>/dev/null`
   `ln -sf ~/.myconfig/tmux/tmux.conf ~/.tmux.conf`
end
