desc "Install tmux"
task :install do
   `sudo apt-add-repository ppa:simono/dev-tools`
   `sudo apt-get update`
   `sudo apt-get install tmux`
end

desc "Creates needed symlinks"
task :link do
   `mv -f ~/.tmux.conf ~/.tmux.conf.old 2>/dev/null`
   `ln -sf ~/.myconfig/tmux/tmux.conf ~/.tmux.conf`
end
