desc "Install zsh and oh-my-zsh"
task :install do
   uname = `uname`.strip
   if uname == "Linux"
      `sudo apt-get install zsh wget`
   else
      `brew install wget`
   end

   sh "wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh"

   if uname == "Linux"
      puts "*****************************************"
      puts "*** when prompted, enter /usr/bin/zsh ***"
      puts "*****************************************"

      sh "chsh"
   end

   puts "******************************"
   puts "*** YOU NEED TO LOGOUT NOW ***"
   puts "******************************"
end

desc "Creates needed symlinks"
task :link do
   `mv -f ~/.zshrc ~/.zshrc.old 2>/dev/null`
   `ln -sF ~/.myconfig/zsh/zshrc ~/.zshrc 2>/dev/null`
end

