# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(bundler git rails3 ruby history-substring-search)

source $ZSH/oh-my-zsh.sh

#########################################################################
#########################################################################

# Linux: 
if [[ `uname` == "Linux" ]]; then 
   PATH=$PATH:/home/rafaelvega/Scripts:/home/rafaelvega/Scripts/jack
   PATH=$PATH:/home/rafaelvega/TechStuff/Android/android-sdk-linux/tools:/home/rafaelvega/TechStuff/Android/android-sdk-linux/platform-tools
   PATH=$PATH:/opt/microchip/xc8/v1.10/bin
   export PATH

   # Alias for ack-grep
   alias ack='ack-grep'

   # Alias for gnome-open
   alias open='/usr/bin/gnome-open'

   # Gvim open on same window, new tab
   alias gvim='/home/rafaelvega/Scripts/open-vim-new-tab.sh'


# MacOS:
else
   # NodeJS
   export NODE_PATH=/usr/local/lib/node_modules:$NODE_PATH

   export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:$PATH
   export PATH=/usr/local/share/npm/lib/node_modules/brunch/bin:$PATH

   alias gvim=mvim
   alias gitg=gitx
fi

# Use gvim for everything
export EDITOR=gvim

# Ruby versions
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Tell make to use parallelism for faster builds
# export NUMCPUS=`grep -c '^processor' /proc/cpuinfo`
export NUMCPUS=4
export MAKEFLAGS="-j$((NUMCPUS*2)) --load-average=$((NUMCPUS*2))"

alias rake='noglob rake'

# Vaca 
# ~/Scripts/cow.sh
fortune | cowsay
